import logging

console = logging.StreamHandler()
logger = logging.getLogger("loggger")
if logger.hasHandlers():
    logger.handlers.clear()
logger.addHandler(console)
logger.setLevel(logging.INFO)

date_formats = ("%m/%d/%y", "%d.%m.%Y")

headers_eng = {
    ("STAT", "STAT (STAT)"): "stat",
    ("ND", "ND (Номер декларации)"): "declaration_number",
    ("G32", "G32 (Номер товара по ГТД)"): "the_number_of_the_goods_is_the_following",
    ("G33", "G33 (Код товара по ТН ВЭД)"): "commodity_code_according_to_hs",
    ("G071", "G071 (код таможни)"): "customs_code",
    ("G072", "G072 (Дата регистрации)"): "date_of_registration",
    ("G073", "G073 (Номер бланка)"): "g074",
    ("GD1", "GD1 (Дата выпуска)"): "release_date",
    ("G541D", "G541D (Дата свидетельства брокера)"): "date_of_the_brokers_certificate",
    ("G230", "G230 (Дата курса валюты)"): "currency_exchange_rate_date",
    ("G24", "G24 (характер сделки)"): "g25",
    ("G011", "G011 (Направление перемещения)"): "direction_of_movement",
    ("G0121", "G0121 (Таможенный режим)"): "customs_regime",
    ("G021", "G021 (ИНН отправителя)"): "senders_tin",
    ("G021_REGION",): "g021_region",
    ("G022", "G022 (Наименование отправителя)"): "senders_name",
    ("G023", "G023 (Адрес отправителя)"): "address",
    ("G19", "G19 (Признак контейнерных перевозок)"): "a_sign_of_container_transportation",
    ("G031",): "g032",
    ("G032", "G032 (Кол-во ТД1/2 или ТД3/4)"): "number_of_td1_2_or_td3_4",
    ("G04", "G04 (общее кол-во листов спецификаций)"): "g05",
    ("G05", "G05 (Всего наименований товаров)"): "total_product_names",
    ("G06", "G06 (Кол-во мест)"): "number_of_seats",
    ("G07", "G07 (Тип ГТД)"): "type_of_gtd",
    ("G081", "G081 (ИНН получателя)"): "recipients_tin",
    ("G081_REGION",): "g081_region",
    ("G082", "G082 (Наименование получателя)"): "name_of_the_recipient",
    ("G0831", "G0831 (Код страны получателя)"): "recipients_country_code",
    ("G083", "G083 (Адрес получателя)"): "recipients_address",
    ("G091", "G091 (ИНН контрактодержателя)"): "inn_of_the_contract_holder",
    ("G092", "G092 (Наименование контрактодержателя)"): "name_of_the_contract_holder",
    ("G0931", "G0931 (Код страны контрактодержателя)"): "country_code_of_the_contract_holder",
    ("G093", "G093 (Адрес контрактодержателя)"): "address_of_the_contract_holder",
    ("G097",): "g098",
    ("xCONTAINER", "CONTAINER"): "xcontainer",
    ("G11", "G11 (Код торгующей страны)"): "code_of_the_trading_country",
    ("G12", "G12 (Общая таможенная стоимость по ГТД)"): "the_total_customs_value_of_the_gtd",
    ("G121",): "the_currency_code_is_there_costs",
    ("G141", "G141 (ИНН декларанта)"): "declarants_inn",
    ("G142", "G142 (Наименование декларанта)"): "name_of_the_declarant",
    ("G1431", "G1431 (Код страны нахождения декларанта)"): "the_code_of_the_declarants_country_of_residence",
    ("G143", "G143 (Адрес декларанта)"): "declarants_address",
    ("G147",): "g148",
    ("CONTSTAT",): "contstat",
    ("G0231", "G0231 (Код страны отправителя)"): "senders_country_code",
    ("G34", "G34 (Код страны происхождения)"): "country_of_origin_code",
    ("G15", "G15 (Страна отправления)"): "country_of_departure",
    ("G15A", "G15A (Код страны отправления)"): "country_code_of_departure",
    ("G16", "G16 (Страна происхождения)"): "country_of_origin",
    ("G17A", "G17A (Код страны назначения)"): "destination_country_code",
    ("G17B", "G17B (Страна назначения)"): "destination_country",
    ("G180",): "g180",
    ("G300", "G300 (Тип информации)"): "type_of_information",
    ("G202", "G202 (Условие поставки)"): "delivery_condition",
    ("G2021", "G2021 (Пункт поставки товара)"): "point_of_supply_of_goods",
    ("G084B",): "g084b",
    ("G087",): "g088",
    ("G094B",): "g094b",
    ("G221", "G221 (Букв.код валюты контракта)"): "letters_contract_currency_code",
    ("G222", "G222 (Общая фактурная стоимость по ГТД)"): "total_invoice_value_for_gtd",
    ("G23", "G23 (Курс валюты)"): "currency_exchange_rate",
    ("G024B",): "g024b",
    ("G027",): "g028",
    ("G144B",): "g144b",
    ("G29",): "customs_code_at_the_border",
    ("G31_1", "G31_1 (Наименование и характеристики товаров)"): "name_and_characteristics_of_the_goods",
    ("G31_11", "G31_11 (Фирма-изготовитель)"): "manufacturer_company",
    ("G31_12", "G31_12 (Товарный знак, патент)"): "trademark_patent",
    ("G31_13", "G31_13 (Страна происхождения)"): "country_of_origin_2",
    ("G281", "G281 (Банковские реквизиты)"): "bank_requisites",
    ("G31_2", "G31_2 (Кол-во грузовых мест)"): "number_of_cargo_spaces",
    ("G31_20",): "package_availability_code",
    ("G31_21",): "g31_21",
    ("G31_4",): "g31_4",
    ("G31_41",): "g31_41",
    ("G31_3", "G31_3 (Кол-во контейнеров)"): "number_of_containers",
    ("G31_7", "G31_7 (Кол-во товара в доп.ед.)"): "number_of_goods_in_additional_units",
    ("G31_71", "G31_71 (Наименование доп.ед.)"): "the_name_of_the_additional_unit",
    ("G31_8", "G31_8 (Кол-во товара во второй ед.изм.)"): "the_number_of_goods_in_the_second_unit_change",
    ("G31_81", "G31_81 (Наименование второй ед.изм.)"): "the_name_of_the_second_unit_is",
    ("G31_82", "G31_82 (Код второй ед.изм.)"): "the_code_of_the_second_unit",
    ("G31_9",): "number_of_goods_of_the_third_unit_of_change",
    ("G31_91",): "naim_the_third_unit_of_change",
    ("G31_92",): "the_code_of_the_third_unit",
    ("G36", "G36 (Преференции, особ.уплаты)"): "preferences_special_payments",
    ("G37", "G37 (Процедура)"): "procedure",
    ("G38", "G38 (Вес нетто, кг)"): "net_weight_kg",
    ("G35", "G35 (Вес брутто, кг)"): "gross_weight_kg",
    ("NETTOBRUTTO",): "nettobrutto",
    ("G39", "G39 (Квота)"): "quota",
    ("G3911",): "g3911",
    ("G3912",): "g3912",
    ("G392",): "g392",
    ("G41A", "G41A (Код доп.ед.изм.)"): "the_code_of_the_additional_unit",
    ("G42", "G42 (Фактурная стоимость)"): "invoice_value",
    ("G43", "G43 (Признак КТС)"): "a_sign_of_the_ccc",
    ("G430", "G430 (Метод определения ТС)"): "vehicle_detection_method",
    ("G45", "G45 (Таможенная стоимость)"): "customs_value_rub",
    ("G452",): "g453",
    ("G46", "G46 (Статистическая стоимость, USD.)"): "statistical_cost_usd",
    ("RUBEDIZM",): "rubedizm",
    ("USDEDIZM",): "usdedizm",
    ("USDKG", "USDKG (USD за КГ)"): "usd_for_kg",
    ("G474DOL",): "the_amount_of_the_border_is_47_in_usd",
    ("G474USD",): "g474usd",
    ("G474RUB",): "the_amount_of_the_border_47_in_rur",
    ("G541", "G541 (Номер свидетельства брокера)"): "brokers_certificate_number",
    ("G541_INN", "G541_INN (ИНН брокера)"): "brokers_inn",
    ("G541_NAM", "G541_NAM (Наименование брокера)"): "brokers_name",
    ("G541_ADR", "G541_ADR (Адрес и контакты брокера)"): "brokers_address",
    ("G5441", "G5441 (ФИО заполнителя)"): "placeholders_full_name",
    ("G5442",): "placeholder_phone_number",
    ("G5447",): "position_of_the_placeholder",
    ("VID_KTC",): "availability_of_the_ccc",
    ("GD0", "GD0 (Код завершения таможенного оформления)"): "code_for_completing_customs_clearance",
    ("GD2", "GD2 (ЛНП долж.лица)"): "lnp_must_faces",
    ("G3010", "G3010 (Тип документа)"): "document_type",
    ("G301", "G301 (Свидетельство СВХ)"): "certificate_of_svh",
    ("G30", "G30 (Название станции/склада)"): "name_of_the_station_warehouse",
    ("G3012", "G3012 (Код там. органа)"): "the_code_is_there",
    ("TYP_DTC",): "typ_dtc",
    ("MODELS",): "models",
    ("BANK_REGNUM",): "bank_regnum",
    ("BANK_BRANCH",): "bank_branch",
    ("G331",): "g332",
    ("G30_ADDRESS",): "g30_address",
    ("FILENAME",): "filename",
    ("updated",): "updated",
    ("G45A",): "g45a",
    ("G45AE",): "g45ae",
    ("G474DOL_U",): "g474dol_u",
    ("CBX",): "tsw",
    ("CONTR",): "contr",
    ("KDT_TYPE",): "kdt_type",
    ("NOTE",): "note",
    ("FIRM",
     "FIRM (Доп.информация о контрактодержателе (Росстат))"):
    "additional_information_about_the_contract_holder_from_rosstat",
    ("G0131",): "g0131",
    ("G020",): "g020",
    ("G023CITY",): "senders_city",
    ("G023POST",): "senders_index",
    ("G023STREET",): "senders_address",
    ("G023SUBD",): "senders_area",
    ("G080",): "g080",
    ("G090",): "g090",
    ("G11C",): "g11c",
    ("G140",): "g141",
    ("G15AC",): "g15ac",
    ("G18", "G18 (кол-во транспортных средств)"): "g18",
    ("G21", "G21 (кол-во транспортных средств на границе)"): "g21",
    ("G210",): "g210",
    ("G221C",): "g221c",
    ("TOVG",): "product_information_from_applications",
    ("TEXT1",): "the_reverse_side_of_the_gtd",
    ("G30SUBD", "G30SUBD (Район склада)"): "warehouse_area",
    ("G42RUB", "G42RUB (Фактурная стоимость в рублях)"): "invoice_cost_rub",
    ("G25",): "type_of_transport_at_the_border",
    ("G30A",): "g30a",
    ("G5411", "G5411 (Номер договора брокера с декларантом)"): "g5412",
    ("G26",): "type_of_transport_within_the_country",
    ("G5411D", "G5411D (Дата договора брокера с декларантом)"): "g5411d",
    ("NTRANS",): "ntrans",
    ("G30STREET", "G30STREET (Улица склада)"): "warehouse_street",
    ("G30CITY", "G30CITY (Город склада)"): "warehouse_city",
    ("VIDTRANS",): "vidtrans"
}

list_needed_columns = list(headers_eng.values())

list_of_float_type = ['the_total_customs_value_of_the_gtd', 'total_invoice_value_for_gtd', 'currency_exchange_rate',
                      'number_of_goods_in_additional_units', 'the_number_of_goods_in_the_second_unit_change',
                      'net_weight_kg', 'gross_weight_kg', 'invoice_value', 'customs_value_rub', 'statistical_cost_usd',
                      'usd_for_kg', 'quota']
list_of_int_type = ['number_of_seats', 'number_of_cargo_spaces']
list_of_date_type = ['date_of_registration', 'release_date', 'date_of_the_brokers_certificate',
                     'currency_exchange_rate_date']
list_of_str_type = ['stat']
