
HEADERS_ENG = {
    ("ND ГрА Регистрационный номер ДТ",): "declaration_number",
    ("G32",): "the_number_of_the_goods_is_the_following",
    ("G07 вид гтд",): "abbreviation_type_of_gtd",
    ("вид гтд",): "type_of_gtd",
    ("G072 Дата регистрации ДТ",): "date_of_registration_declaration",
    ("GD1 Дата изменения статуса ДТ",): "release_date",
    ("G071 ТО декларирования",): "customs_code",
    ("наименование ТО декларирования",): "customs_department",
    ("адрес ТО декларирования",): "customs_department_address",
    ("Бизнес-партнер",): "business_partner",
    ("Адрес Бизнес-партнера",): "business_partner_address",
    ("УВЭД РНН/ИИН/БИН",): "external_economic_activity_member_rnn_iin_bin",
    ("УВЭД Наименование",): "external_economic_activity_member",
    ("УВЭД Адрес",): "external_economic_activity_member_address",
    ("G011 Тип перемещения",): "direction",
    ("G0121 Таможенная процедура",): "customs_regime_code",
    ("Наименование таможенной процедуры",): "customs_regime",
    ("G11 Торгующая страна",): "trading_country_code",
    ("G11 Наименование торгующей страны",): "trading_country",
    ("G15A Код страны отправления",): "country_of_departure_code",
    ("G15 Наименование страны отправления",): "country_of_departure",
    ("G16 Страна происхождения",): "country_of_origin_code",
    ("G16 Наименование страны происхождения",): "country_of_origin",
    ("G17A Код страны назначения",): "destination_country_code",
    ("G17 Наименование страны назначения",): "destination_country",
    ("G202 Условия поставки",): "delivery_condition_code",
    ("Условия поставки",): "delivery_condition",
    ("G2021 место поставки",): "point_of_supply_of_goods",
    ("G221 Код валюты контракта",): "contract_currency_code",
    ("валюта контракта",): "contract_currency",
    ("G23 Курс валюты НБ РК",): "currency_exchange_rate",
    ("G33 Код товара по ТН ВЭД ТС",): "commodity_code_according_to_hs",
    ("ТНВЭД ТС",): "commodity_group",
    ("G31_1 Наименование товаров 1",): "name_and_characteristics_of_the_goods_1",
    ("G31_1 Наименование товаров 2",): "name_and_characteristics_of_the_goods_2",
    ("G31_11 Производитель",): "manufacturer_company",
    ("G31_12 Товарный знак",): "trademark_patent",
    ("G31_14 Марка товара",): "good_brand",
    ("Колво деи ТОВГ",): "number_of_TOVG_in_additional_unit",
    ("Наименование деи ТОВГ",): "the_name_of_the_additional_unit_of_TOVG",
    ("Гр41 Количество в ДЕИ",): "number_of_goods_in_additional_unit",
    ("Гр41 Код ДЕИ",): "the_code_of_the_additional_unit",
    ("Гр41 Наименование ДЕИ",): "the_name_of_the_additional_unit",
    ("G35 Вес брутто (кг)",): "gross_weight_kg",
    ("G38 Вес нетто (кг)",): "net_weight_kg",
    ("G42 Фактурная стоимость",): "invoice_value",
    ("G45 Таможенная стоимость",): "customs_value_rub",
    ("G46 Статистическая стоимость",): "statistical_cost_usd",
    ("G25 Вид транспорта на границе",): "type_of_transport_at_the_border",
    ("транспорт на границе",): "transport_at_the_border",
    ("G26 Вид транспорта внутри страны",): "type_of_transport_within_the_country",
    ("транспорт внутри страны",): "transport_within_the_country",
    ("Полное наименование",): "full_name_of_external_economic_activity_member",
    ("Краткое наименование",): "short_name_of_external_economic_activity_member",
    ("Дата регистрации",): "date_of_registration",
    ("Дата перерегистрации",): "re_registration_date",
    ("Руководитель",): "director_full_name",
    ("TE",): "TE",
    ("Область",): "region",
    ("Наименование района",): "district",
    ("Название населенного пункта",): "city",
    ("Индекс",): "index",
    ("Адрес",): "address",
    ("Телефон",): "telephone_number",
    ("E-mail",): "email",
    ("Наименование ситуации",): "status_at_upload_date",
    ("OKED",): "okved_activity_main_type",
    ("Наименование вида деятельности",): "activity_main_type",
    ("Вторичный ОКЭД",): "okved_activity_other_types",
    ("Наименование сектора экономики",): "economy_sector",
    ("КРП",): "KRP",
    ("Размерность предприятий",): "enterprise_size",
    ("Численность",): "employees_number_at_upload_date",
    ("Наименование вида собственности",): "name_of_the_type_of_property",
    ("Страна партнер",): "partner_country",
    ("БИН/ИИН контрактодержателя",): "iin_bin_of_the_contract_holder",
    ("контрактодержатель",): "contract_holder",
    ("адрес контрактодержателя",): "contract_holder_address",
    ("БИН/ИИН декларанта",): "iin_bin_of_the_declarant",
    ("декларант",): "declarant",
    ("Артикул товара",): "product_sku",
    ("Сорт",): "grade",
    ("Наименование сортимента для 4403",): "assortment_name",
    ("Описание",): "assortment_name_description",
    ("Описание1",): "assortment_name_description_1",
    ("Описание2",): "assortment_name_description_2",
    ("количество деи из оп товара 1",): "number_of_goods_in_additional_unit_from_description_1",
    ("деи из оп товара 1",): "the_name_of_the_additional_unit_from_description_1",
    ("количество деи из оп товара 2",): "number_of_goods_in_additional_unit_from_description_2",
    ("деи из оп товара 2",): "the_name_of_the_additional_unit_from_description_2",
    ("Количество ДЕИ2",): "number_of_goods_in_additional_unit_2",
    ("Код ДЕИ2",): "the_code_of_the_additional_unit_2",
    ("Описание ДЕИ2",): "the_name_of_the_additional_unit_2",
    ("Статус ДТ",): "declaration_status",
    ("Итого фактурная стоимость",): "the_total_invoice_value_of_the_gtd",
    ("Код метода определения стоимости",): "code_of_the_method_for_determining_the_customs_value",
    ("Графа 43.2",): "customs_value_adjustment_flag_code"
}

LIST_OF_FLOAT_TYPE: list = [
    'currency_exchange_rate',
    'number_of_goods_in_additional_unit',
    'gross_weight_kg',
    'net_weight_kg',
    'invoice_value',
    'customs_value_rub',
    'statistical_cost_usd',
]

LIST_OF_INT_TYPE: list = [
    'the_number_of_the_goods_is_the_following',
    'customs_regime_code',
    'number_of_TOVG_in_additional_unit',
    'type_of_transport_at_the_border',
    'type_of_transport_within_the_country'
]

LIST_OF_DATE_TYPE: list = [
    'date_of_registration_declaration',
    'release_date',
    'date_of_registration',
    're_registration_date',
]

LIST_OF_STR_TYPE: list = [

]

